version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "church-hosting"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-dvn9rntjvs32"
s3_prefix = "church-hosting"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
