AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  church-hosting

  Sample SAM Template for church-hosting
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  
  #
  # API GATEWAY
  #
  
  APIgateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      GatewayResponses:
        UNAUTHORIZED:
          StatusCode: 401
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
        ACCESS_DENIED:
          StatusCode: 403
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
        DEFAULT_5XX:
          StatusCode: 500
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
        RESOURCE_NOT_FOUND:
          StatusCode: 404
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"  
      Cors:
         AllowMethods: "'*'"
         AllowHeaders: "'*'"
         AllowOrigin: "'*'"
      Auth:
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          MainAuthorizer:
            UserPoolArn: "arn:aws:cognito-idp:us-east-1:315327088521:userpool/us-east-1_194gN8sei"
        DefaultAuthorizer: MainAuthorizer

  #
  # FUNCTIONS
  #

  NewSiteFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: newsite/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Policies:
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /newsite
            Method: get
            RestApiId: !Ref APIgateway

  EditSiteFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: editsite/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Policies:
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /editsite
            Method: post
            RestApiId: !Ref APIgateway

  #
  # TABLES
  #

  BucketTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: catholichosting-bucket-table
      PrimaryKey:
        Type: String
        Name: bucket



Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${APIgateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

